version: '3.8'

services:
  minio:
    container_name: minio_server
    build: ./minio
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  weaviate:
    container_name: weaviate_server
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 's3_backup'
      BACKUP_S3_BUCKET: 'weaviate-backups'
      BACKUP_S3_ENDPOINT: 'http://localhost:9000'
      BACKUP_S3_ACCESS_KEY_ID: 'minio'
      BACKUP_S3_SECRET_ACCESS_KEY: 'minio123'
      BACKUP_S3_USE_SSL: 'false'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - ./weaviate/data:/var/lib/weaviate
    depends_on:
      - minio

