name: Weaviate POC Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Install Docker Compose plugin
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      # 4. Spin up MinIO & Weaviate via Docker Compose
      - name: Launch POC stack
        run: docker compose -f build-context-docker-compose.yaml up -d

      # 5. Wait for Weaviate to be ready
      - name: Wait for Weaviate service
        run: |
          echo "Waiting for Weaviate to start..."
          sleep 15

      # 6. Create Weaviate schema
      - name: Create Weaviate Schema
        run: |
          curl -X POST -H "Content-Type: application/json" \
            --data @./weaviate/schema.json \
            http://localhost:8080/v1/schema

      # 7. Index sample data
      - name: Index Data
        run: |
          curl -X POST -H "Content-Type: application/json" \
            --data @./weaviate/data.json \
            http://localhost:8080/v1/objects

      # 8. Perform Backup to MinIO
      - name: Perform Backup
        run: |
          curl -X POST -H "Content-Type: application/json" \
            --data '{"id":"backup-id"}' \
            http://localhost:8080/v1/backups/s3

      # 9. Restore Data from Backup
      - name: Restore Data
        run: |
          curl -X POST http://localhost:8080/v1/backups/s3/backup-id/restore

      # 10. Tear down
      - name: Clean up
        run: docker compose -f build-context-docker-compose.yaml down
