name: Weaviate POC Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yaml up -d

    - name: Wait for Weaviate to be ready
      run: |
        echo "Waiting for Weaviate service to start..."
        sleep 30 # waits for 30 seconds

    - name: Create Weaviate Schema
      run: |
        curl -X POST -H "Content-Type: application/json" \
        --data '{"classes": [{"class": "Article", "description": "A class to store articles", "properties": [{"name": "title", "dataType": ["string"], "description": "The title of the article"}, {"name": "content", "dataType": ["text"], "description": "The content of the article"}, {"name": "datePublished", "dataType": ["date"], "description": "The date the article was published"}, {"name": "url", "dataType": ["string"], "description": "The URL of the article"}]}, {"class": "Author", "description": "A class to store authors", "properties": [{"name": "name", "dataType": ["string"], "description": "The name of the author"}, {"name": "articles", "dataType": ["Article"], "description": "The articles written by the author"}]}]}' \
        http://localhost:8080/v1/schema

    - name: Index Data
      run: |
        curl -X POST -H "Content-Type: application/json" \
        --data @./weaviate/data.json http://localhost:8080/v1/objects

    - name: Perform Backup
      run: |
        curl -X POST -H "Content-Type: application/json" \
        --data '{"id": "backup-id"}' http://localhost:8080/v1/backups/s3

    - name: Restore Data
      run: |
        curl -X POST -H "Content-Type: application/json" \
        http://localhost:8080/v1/backups/s3/backup-id/restore

    - name: Clean up
      run: docker-compose down