name: Docker Compose Test Build and Push

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker Compose plugin
        uses: docker/setup-compose-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Compose Build
        run: docker compose -f build-context-docker-compose.yaml build

      - name: Docker Compose Up
        run: docker compose -f build-context-docker-compose.yaml up -d

      - name: Push Docker images to Docker Hub
        run: docker compose -f build-context-docker-compose.yaml push

      - name: Docker Compose Down
        run: docker compose -f build-context-docker-compose.yaml down
